python simulated_averaging.py --fraction 0.1 \
--batch-size 128 \
--test-batch-size 256 \
--lr 0.001 \
--gamma 0.998 \
--num_nets 50 \
--fl_round 500 \
--part_nets_per_round 10 \
--local_train_period 2 \
--adversarial_local_training_period 2 \
--dataset imagenet \
--model resnet18 \
--fl_mode fixed-freq \
--attacker_pool_size 100 \
--defense_method no-defense \
--attack_method blackbox \
--attack_case edge-case \
--model_replacement False \
--project_frequency 10 \
--eps 2 \
--adv_lr 0.001 \
--prox_attack False \
--poison_type southwest \
--norm_bound 2 \
--device=cuda:2